config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :industries
  resources :companies


end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :industries
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_and_belongs_to_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
    @industries = @companies.industries.all
  end

  def show
    @company = Company.find(params[:id])
    @industry = Industry.find(params[:industry_id])
    @company.industry_id = @industry.id
  end

  def create
    @industry = Industry.find(params[:industry_id])
    @company = Company.new(company_params)
    @company.industry_id = @industry.id
      if @company.save
        redirect_to company_path(@company), notice: "Company was successfully created!"
      else
      render :new
      end
    end

    def edit
      @industry = Industry.find(params[:industry_id])
      @company = Company.find(params[:id])
    end

  def update
    @industry = Industry.find(params[:industry_id])
    @company = Company.find(params[:id])
      if @company.update(company_params)
        redirect_to company_path(@company)
      else
        render :edit
    end
  end

  def destroy
    @industry = Industry.find(params[:industry_id])
    @company = Company.find(params[:id])
    @company.industry_id = @industry.id
    @company.destroy
    redirect_to company_path(@company), notice:'Company was successfully deleted!'
  end

  private
    def company_params
      params.require(:company).permit(:name, :description, :industry_id, :created_at, :updated_at)
    end

end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController

  def index
    @industries = Industry.all
    @companies = @industries.companies.all
  end

  def show
    @company = Company.find(params[:company_id])
    @industry = Industry.find(params[:id])
    @industry.company_id = @company.id
  end

  def create
    @company = Company.find(params[:company_id])
    @industry = Industry.new(industry_params)
    @industry.company_id = @company.id
      if @industry.save
        redirect_to industry_path(@industry), notice: "Industry was successfully created!"
      else
      render :new
      end
    end

    def edit
      @company = Company.find(params[:company_id])
      @industry = Industry.find(params[:id])
    end

  def update
    @company = Company.find(params[:company_id])
    @industry = Industry.find(params[:id])
      if @industry.update(industry_params)
        redirect_to industry_path(@industry)
      else
        render :edit
    end
  end

  def destroy
    @company = Company.find(params[:company_id])
    @industry = Industry.find(params[:id])
    @industry.company_id = @company.id
    @industry.destroy
    redirect_to industry_path(@industry), notice:'Industry was deleted!'
  end

  private

  def industry_params
    params.require(:industry).permit(:name, :description, :company_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/edit.html.erb
<h1>Edit Industry</h1>

<%= form_for ([@industry, @company]) do |f| %>

  <div>
    <%= f.label :name%>
    <%= f.text_field :name %><br>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %><br>
  </div>


<%= f.submit%>

<% end %>

app/views/companies/index.html.erb
<h1>All Companies</h1>

<%= link_to 'Create New Company', new_company_path %>

<table>
  <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Created_at</th>
      <th>Updated_at</th>
    </tr>
    <tbody>
      <% @company.each do |company| %>
        <tr>
          <td><%=link_to company.name, company_path(@company)%></td>
          <td><%=company.description %></td>
          <td><%=company.price %></td>
          <td><%=company.created_at %></td>
          <td><%=company.updated_at %></td>
       </tr>
          <% end %>
    </tbody>
</table>

app/views/companies/new.html.erb
<h1>Create New Industry</h1>

<%= form_for ([@industry, @company]) do |f| %>

  <div>
    <%= f.label :name%>
    <%= f.text_field :name %><br>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %><br>
  </div>


<%= f.submit%>

<% end %>

app/views/companies/show.html.erb
<%= link_to 'Edit', edit_company_path(@company) %>
<%= link_to 'Delete', company_path, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %> %>


<h1> <%= @company.name %></h1>


  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Created At</th>
      <th>Update At</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @company.name %></td>
      <td><%= @company.description %></td>
      <td><%= @company.price %></td>
      <td><%= @company.created_at %></td>
      <td><%= @company.updated_at %></td>
    </tr>
  </tbody>


<h2>Industries</h2>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
  <% @company.industries.each do |industry| %>
    <tr>
      <td><%= industry.name %></td>
      <td><%= industry.description %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/industries/edit.html.erb
<h1>Edit Industry</h1>

<%= form_for ([@company, @industry]) do |f| %>

  <div>
    <%= f.label :name%>
    <%= f.text_field :name %><br>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>

<%= f.submit%>

<% end %>

app/views/industries/index.html.erb
<h1>All Industries</h1>

<%= link_to 'Create New Industry', new_industry_path %>

<table>
  <tr>
      <th>Name</th>
      <th>Created At</th>
      <th>Updated At</th>
  </tr>

    <tbody>
      <%= @industries.each do |industry| %>
        <tr>
          <td><%= link_to industry.name, industry_path(@industry) %></td>
          <td><%=industry.created_at %></td>
          <td><%=industry.updated_at %></td>
       </tr>
          <% end %>
    </tbody>
</table>

app/views/industries/new.html.erb
<h1>Create New Industry</h1>

<%= form_for ([@company, @industry]) do |f| %>

  <div>
    <%= f.label :name%>
    <%= f.text_field :name %><br>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </div>


<%= f.submit%>

<% end %>

app/views/industries/show.html.erb
<%= link_to 'Delete', industry_path, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %> %>



<h1> <%= @industry.name %></h1>


  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created At</th>
      <th>Update At</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @industry.name %></td>
      <td><%= @industry.description %></td>
      <td><%= @industry.created_at %></td>
      <td><%= @industry.updated_at %></td>
    </tr>
  </tbody>


<h2>Companies</h2>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
  <% @industry.companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.description %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Companies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<%= link_to 'All Industries', industries_path %>
<%= link_to 'All Companies', companies_path %>